### ISSUE TITLE
A complaint

### ISSUE THREAD

**Issue by timet12** [jonas747/yagpdb#1011]
The problem is that the auto moderator prohibits links and invitations in tickets, for example, a person leaves evidence there a link to YouTube, etc. and the bot bans him, this is a ridiculous decision: you can select not only channels, but categories

**Comment by BlackWolfWoof** [comment]
For advanced stuff you can use automod v2.

**Comment by timet12** [comment]
> Для продвинутых задач вы можете использовать automod v2.

Спасибо! Решено. Закрыто.
