### ISSUE TITLE
Role commands

### ISSUE THREAD

**Issue by timet12** [jonas747/yagpdb#1012]
How to use Role commands Customize and use?

**Comment by l-zeuch** [comment]
![this isn't the support channel](https://user-images.githubusercontent.com/71897876/127374977-9fe8a5b1-c5f0-4e2e-ae56-9be0d7c81836.png)

**Comment by DaviiD1337** [comment]
Imagine. 
_Invite link to support server anyway: https://discord.gg/pGXTpGs_
