### ISSUE TITLE
allowed intents 

### ISSUE THREAD

**Issue by Space-Clustercompany** [jonas747/yagpdb#1018]
i am having an error 

ERRO [GATEWAY] got close frame, code: 4014, Msg: "Disallowed intent(s)."  stck="discordgo.(*GatewayConnection).handleCloseFrame:gateway.go:1045" shard=0 connid=1
ERRO [GATEWAY] Disabled or not whitelisted for one of the intents passed to gateway open  stck="discordgo.(*GatewayConnection).handleCloseFrame.func1:gateway.go:1069" connid=1 shard=0
INFO [Shard Manager] [0/1] Disconnected            stck="jdshardmanager.(*Manager).LogConnectionEventStd:dshardmanager.go:269"
ERRO [GATEWAY] error reading next gateway message: EOF: EOF  stck="discordgo.(*GatewayConnection).onError:gateway.go:1352" shard=0 connid=1

**Comment by Space-Clustercompany** [comment]
allow both the intents things at the devloper portal bot page

**Comment by Wolveric** [comment]
So... hoster error...? I can't break down that log/error at all, and is that what you're saying...?

**Comment by l-zeuch** [comment]
Intents are required since a while right now, somehow not showing up in the readme though...

**Comment by l-zeuch** [comment]
> I can't break down that log/error at all

Error clearly says "disallowed intents" "Disabled or not whitelisted for one of the intents passed to gateway open"
