### ISSUE TITLE
Youtube: Multiple announcement posts

### ISSUE THREAD

**Issue by TheDarkPreacher** [jonas747/yagpdb#111]
The bot started multi-posting an announce for a video today. posted the same announcement about 20 times. started after the issues Discord had today.

**Comment by jonas747** [comment]
this was related to the issues with discord, if it failed sending the message, it will retry, and discord did fail, but still seemed to post the messages after a long delay which resulted in the bot spamming, i'm not sure how i would deal with this, or if i can, but ill look into it.

**Comment by buthed010203** [comment]
Dead tbh @jonas747
