### ISSUE TITLE
More neutrally bot avatar

### ISSUE THREAD

**Issue by TomberWolf** [jonas747/yagpdb#114]
Do you think you could change the bot's icon to a more neutrally one?

![booking-slack-bot-icon 1](https://user-images.githubusercontent.com/9993839/34442025-b0842218-ecbf-11e7-91a0-17c7407c9fd4.png)
![bot-framework-default-7 1](https://user-images.githubusercontent.com/9993839/34442035-bc0854ce-ecbf-11e7-981b-a14a2f5b1b70.png)

**Comment by jonas747** [comment]
no
