### ISSUE TITLE
Suggestion: Custom Command Autodelete

### ISSUE THREAD

**Issue by timcampy118** [jonas747/yagpdb#120]
Allow option to auto delete the command and its trigger like you do with normal commands. Currently possible workaround with Exec Clear but would be nice.

**Comment by buthed010203** [comment]
This ^

**Comment by buthed010203** [comment]
@jonas747 close

**Comment by thislooksfun** [comment]
Found it!

For others looking in the future, you want `deleteTrigger` and/or `deleteResponse` from [the docs](https://docs.yagpdb.xyz/reference/templates#functions)

Example:
```
{{ deleteTrigger 0 }}

Good morning, {{.User.Username}. Your mission, should you choose to accept it,
is to navigate the yagpdb docs and find hidden functions buried deep within the
templates list. As always, should you or any member of your IM Force be caught
or killed, the Secretary will disavow all knowledge of your actions. This message
will self-destruct in five seconds.

{{ deleteResponse 5 }}
```
