### ISSUE TITLE
Suggestion: Streaming - Filter streamer assigned roles based on "Keyworded" games.

### ISSUE THREAD

**Issue by spool1** [jonas747/yagpdb#121]
I am requesting that the streamer role had the ability to check which game a streamer is streaming and/or currently playing based off a whitelist. E.g. `PLAYERUNKNOWNS` where only people streaming & playing that game will be given the streamer role. This would be for servers designed around a specific game in general.

I for one run a community of about 1,500 people for Darkfall: Online and would appreciate a bot that only assigned the "Streamer" role to people that are streaming that game specifically. It would most likely need to be a keyword rather than an exact game as sometimes I can see users in my member list playing `Darkfall: New Dawn` and other times `Darkfall New Dawn` without the `:` - Other bots in the past think these are two different games and would assign two different "Game Roles" to either person.

**Comment by buthed010203** [comment]
@jonas747 Close
