### ISSUE TITLE
Enhancement: Multiple Ignore / Whitelist roles 

### ISSUE THREAD

**Issue by buthed010203** [jonas747/yagpdb#127]
I would like to be able to add multiple whitelist and blacklist roles to things such as automod swear filters etc so I dont need to create a “Staff” role to give to all staff for example. That would be nice with the mee6 lv system so that if User1 reaches lv X they can post links, this way I dont have to create a “Links” role and assign that role to staff and also to User1 alongside his Lv10 role.

Where this could be added:

- [ ] Streaming
- [ ] Automod
- [ ] Logs (to see deleted messages)
- [ ] Reputation
- [ ] Soundboard

**Comment by jonas747** [comment]
I've updated the issue to adhere to the topic, instead of being 5 requests inside 1.
