### ISSUE TITLE
Enhancement: Role Commands “require roles”

### ISSUE THREAD

**Issue by buthed010203** [jonas747/yagpdb#129]
I would like to have an option for role commands to only require one of the selected roles and not all of them.

**Comment by jonas747** [comment]
That's how it currently works, only 1 is required

**Comment by buthed010203** [comment]
I thought the same but actually it reqs all xd why u close then reopen lel

**Comment by jonas747** [comment]
Correction: i was wrong.

**Comment by buthed010203** [comment]
And this is why u aren’t support heh
