### ISSUE TITLE
Role commands: New

### ISSUE THREAD

**Issue by buthed010203** [jonas747/yagpdb#130]
New.....

Delet this

**Comment by jonas747** [comment]
what?

**Comment by buthed010203** [comment]
It says new next to the name

**Comment by jonas747** [comment]
I'm still confused as to what you mean

**Comment by buthed010203** [comment]
Lmao the green block thing that says “New!”

**Comment by jonas747** [comment]
Ah i see

**Comment by buthed010203** [comment]
I dont speak english anymore
