### ISSUE TITLE
Suggestion + Enhancement: Timed bans

### ISSUE THREAD

**Issue by buthed010203** [jonas747/yagpdb#136]
I would like to see timed bans so I could for example do “-ban @buthed010203 1w existing” then it would ban me for a week and unban me after. I would also like to see this as an option for automod, I feel it would be useful.

**Comment by jonas747** [comment]
Added in https://github.com/jonas747/yagpdb/commit/25f95d32f09a6a42e321006e3cf71b5e30417613
