### ISSUE TITLE
Moderation: Add clean filters

### ISSUE THREAD

**Issue by jonas747** [jonas747/yagpdb#145]
The new command system supports switches so something like: `-clean -d 10m` (to delete the messages sent the last 10 minutes, up to 100) 

- [x] Regex filter
- [x] Time filter

**Comment by buthed010203** [comment]
This

**Comment by buthed010203** [comment]
@jonas747 May I suggest -clean -t (for time) instead?

**Comment by jonas747** [comment]
Settled on ma for max age
