### ISSUE TITLE
Enhancement: Help menu update

### ISSUE THREAD

**Issue by buthed010203** [jonas747/yagpdb#162]
I suggest moving the stats + status etc commands to the debug catergory and rename it to devug + stats to prevent cluttering the “fun” section

—
Also, just a question, why is the topcommands command not in the help menu? Its a pretty neat command.

**Comment by ACA30** [comment]
Topcommands is pretty much just a command for server admins, so I guess it could be in the help menu lol... It's technically considered a "secret command". Also, I'm assumimg that when you said "devug + stats" you meant "Debug & Stats" or "Debug + Stats". :)

- Nate

**Comment by buthed010203** [comment]
@ACA30 The top commands isnt even for server admins, if you see the help files on here they have a “dont display in help command” or something property.
