### ISSUE TITLE
Moderation Improvement: Feature to delete commands

### ISSUE THREAD

**Issue by buthed010203** [jonas747/yagpdb#183]
I would like to see an option to instantly delete commands like dyno, this is useful for servers that like to keep their moderation silent
The commands this would be good for are:
Report
Kick
Ban (+IDban)
Warn
Mute
ETC...

**Comment by ACA30** [comment]
@buthed010203 You want YAGPDB to be more like Dyno ;)

**Comment by buthed010203** [comment]
This works now with ccs so imma just close it
