### ISSUE TITLE
Role menus with more than 20 roles

### ISSUE THREAD

**Issue by michelhn** [jonas747/yagpdb#216]
Discord is limiting reactions of one message to 20. If you want to have a group with more than 20 roles, you'd need to create two groups with two menus which is annoying if it should be a single role group.

**Comment by buthed010203** [comment]
Yeah I saw the suggestion of grouping role groups once which would be super handy so I dont have to make the ignored roles all of the roles from the other group. @michelhn That works if you really want them to only have one role at a time tho.

**Comment by sidoncode** [comment]
rolemenu create Roles -skip 20 -nodm -rr
