### ISSUE TITLE
Suggestion:  Add the possibilty of changing the timer of the delete commands

### ISSUE THREAD

**Issue by casKd-dev** [jonas747/yagpdb#218]
**What should it look like?**
Instead of `{{deleteTrigger}}` and `{{deleteResponse}}` it should be:
`{{deleteTrigger *time*}}` and `{{deleteResponse *time*}}`.
Leaving it blank should use the default value **10** so it doesn't break any CC.

**Comment by jonas747** [comment]
Added in https://github.com/jonas747/yagpdb/commit/9c8306fb0af7bf9fa1052239dba25d215bce8b57
