### ISSUE TITLE
Custom Commands: If statements breaking

### ISSUE THREAD

**Issue by casKd-dev** [jonas747/yagpdb#221]
# Problem with if statements

## Steps to reproduce:
_Not really known_

### Example:
```
{{if ne (len .Args) 3}}
	You must enter **2** numbers to roll!
{{else}}
	{{$a := toInt64 (index .Args 1)}}
	{{$b := toInt64 (index .Args 2)}}
	{{if eq $a $b}}
		The numbers **cannot be equal**, or the values are not valid!
	{{else if or (gt $a 99) (gt $b 99) }}
		The numbers **cannot be greater than 99**!
	{{else}}
		{{if gt ($a) ($b)}}
			{{$c := randInt $a $b}}
		{{else if lt ($a) ($b)}}
			{{$c := randInt $b $a}}
		{{end}}
		**{{.User.Username}}**, you have rolled a {{$c}}.
	{{end}}
{{end}}
```

### Expected output:
- Command running correctly and getting the roll output.
### Actual output:
- No output, and $c is not defined.

### What could the problem caused by:
Maybe the method the bot is using to convert the custom commands is not expecting these type of statements.

**Hope we'll get a fix and it won't take too long or too much to fix it!
Thanks for all!**

**Comment by timcampy118** [comment]
Not a issue, remove please.

**Comment by casKd-dev** [comment]
Yes, indeed, figured out that `{{end}}` clears the variable out of the memory

**Comment by buthed010203** [comment]
(I like necroposting) @casKd-dev close this tbh

**Comment by casKd-dev** [comment]
Close #221

**Comment by casKd-dev** [comment]
Close #221
