### ISSUE TITLE
Rolemenu command with message ID doesn't work for messages in other channel

### ISSUE THREAD

**Issue by Pascal27** [jonas747/yagpdb#223]
If you try to use the command `-rolemenu -m <MessageID> <GroupName>` for a message that is not in the channel you are sending this command, you will get an error message:
<img width="468" alt="bildschirmfoto 2018-04-09 um 13 24 12" src="https://user-images.githubusercontent.com/28492184/38495277-520347d0-3bf9-11e8-960c-9a252140ac9e.png">

**Comment by jonas747** [comment]
this is intended and there's no easy way to fix it without also adding a channel argument
