### ISSUE TITLE
Typo: wont

### ISSUE THREAD

**Issue by Pascal27** [jonas747/yagpdb#226]
https://github.com/jonas747/yagpdb/blob/d59f8a4d3ab8d514aa414f970d855776aaa8dfed/rolecommands/menu.go#L177
https://github.com/jonas747/yagpdb/blob/d59f8a4d3ab8d514aa414f970d855776aaa8dfed/rolecommands/menu.go#L179

It should be `won't` instead of `wont`.

**Comment by michelhn** [comment]
This can be closed: https://github.com/jonas747/yagpdb/pull/228
