### ISSUE TITLE
Starting up bot

### ISSUE THREAD

**Issue by JGriffin34432** [jonas747/yagpdb#229]
For some reason, when I try to start up the bot, it says:

**`JoshT@L57569** MINGW64 /c/go-work/src/github.com/jonas747/yagpdb/bot (master)
$ go run bot.go
..\..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:22:2: cannot find package "golang.org/x/sys/windows" in any of:
        C:\Go\src\golang.org\x\sys\windows (from $GOROOT)
        C:\go-work\src\golang.org\x\sys\windows (from $GOPATH)`

**Comment by casKd-dev** [comment]
Check your Go installation, a reinstall may fix it.

**Comment by jonas747** [comment]
closing this cause its dead
