### ISSUE TITLE
Stats link in -stats message not working

### ISSUE THREAD

**Issue by michelhn** [jonas747/yagpdb#232]
I've tried to fix it but I can't find a solution either. It can be fixed [here](https://github.com/jonas747/yagpdb/blob/d59f8a4d3ab8d514aa414f970d855776aaa8dfed/serverstats/plugin_bot.go#L67). The link that it tries to give out is the following: `https://yagpdb.xyz/public/%!s(int64=166207328570441728`. The bot also wrongly interprets the link by putting /stats after the url:
![capture](https://user-images.githubusercontent.com/31596904/38951796-00f03b0c-434a-11e8-802a-67ebb3405571.PNG)

**Comment by jonas747** [comment]
ah should fix this yeah
