### ISSUE TITLE
Autorole not working properly for many members

### ISSUE THREAD

**Issue by Pascal27** [jonas747/yagpdb#236]
At the moment I have the issue that the autorole feature doesn't work properly for many members. Some info about it:

- The bot only assigns roles for members that come online but not for members that are offline
- It should assign a role to around 70 people (server has 860 members)
- 5 roles are selected for "_Ignore people with the following roles_"
- "_Minutes of membership required for role_" is set to 0
- "_Require one of these roles to be present on the member_" is set to no roles
- "_Only assign role when they join, do not give it back it it's removed from them afterwards._" is unticked

**Comment by jonas747** [comment]
`The bot only assigns roles for members that come online but not for members that are offline

That's intended, for now anyways, might change it in the future for the initial assignment.

**Comment by sheisthedevil** [comment]
Made role commands and added reactions. Now every time I click on the reaction i get a messaged from the bot "An error has occurred while assigning the role." How could I possibly fix this?

**Comment by jonas747** [comment]
this is unrelated to the current issue, make a new one.

**Comment by buthed010203** [comment]
To negate this problem, it should always add a role to the user on join or x mins after at least once, another part would be to scan the server daily to see if any roles have to be assigned (even to offline people).

**Comment by jonas747** [comment]
The batch assign function closes this

**Comment by coochiebeans** [comment]
It seems that every time someone joins they automatically get all the roles in our server. How do i fix this issue? I don’t have any auto role so it shouldn’t be doing it.

**Comment by ashishjh-bst** [comment]
> It seems that every time someone joins they automatically get all the roles in our server. How do i fix this issue? I don’t have any auto role so it shouldn’t be doing it.
@coochiebeans 
Please ask in the support server, the link to it is on the dashboard, there are a lot of scenarios that can be causing this, but it will require you to share information like your server id, and a constant stream of communication.

**Comment by coochiebeans** [comment]
Thank you will do!
