### ISSUE TITLE
Suggestion: Auto add reactions to messages in channels

### ISSUE THREAD

**Issue by Dubz** [jonas747/yagpdb#239]
It would be fantastic if there was a way to set a channel (or multiple channels) up for auto reactions.

For instance, if you set up an announcements for events and want to allow users to vote Yes, Maybe, or No as to whether or not they will be attending said event.
Another example being a suggestion/feedback, where users can vote thumbs up/down on a suggestion sent, rather than blowing it up with messages of "I agree" or "I want this too" sort of messages. Keeps the channel more free of general chatter and allows for focus on those points.
You could also add a voting scale for one, and react with 1-5.

Just a few examples of how this could be used, for both productivity and fun.

**Comment by jonas747** [comment]
Adding this functionality to custom commands would be enough i believe, something like a {{addReaction "..."}} function, then you could just set it to run when the message contains something like startvote or whatever

**Comment by buthed010203** [comment]
As Jonas said that would be plenty as you could create a command with a regex trigger of (?) that means any text will trigger the command, you could make it only usable in certain channels

**Comment by buthed010203** [comment]
^ The reactions could be perfectly timed if the {{wait}} thing ever got added....
