### ISSUE TITLE
Suggestion: Edit custom commands

### ISSUE THREAD

**Issue by Dubz** [jonas747/yagpdb#248]
Sometimes I may just want to add another channel to a custom command, or edit some of the functions or triggers. It would be fantastic if I could do that without having to recreate the entire command (possibly from memory if it was made a while ago).

**Comment by LoganK** [comment]
Control Panel/Commands/Custom Commands

Below the creation new section you'll see all of the existing commands. Click the one you want and it provides the option to edit it.

**Comment by Dubz** [comment]
Yeah, I see that now. I didn't realize you need to click on the command to edit it, Is sort of just assumed deleting was the only option since that's the only button shown.

Good to know now, nevermind. Thanks!
