### ISSUE TITLE
Reddit feed not displaying thumbnails 

### ISSUE THREAD

**Issue by egongb** [jonas747/yagpdb#251]
When the bots a Reddit feed, images posted are displayed. When the bot posts a link in a Reddit feed, the thumbnail doesn't generate.

**Comment by jonas747** [comment]
Can you show me the post it wont show the thumdnail for?

**Comment by michelhn** [comment]
https://i.imgur.com/pzahgwd.jpg

works for normal images within the post, but it doesn't display embeds of websites (e.g. images or previews)

**Comment by jonas747** [comment]
Ah i see, yeah thats a bug

**Comment by jonas747** [comment]
Moved back to normal messages for reddit feeds in https://github.com/jonas747/yagpdb/commit/622cd1cd01fd5ad8ec7be91429da0b42781c42a0

**Comment by nqa112** [comment]
it does not show thumbnail when message is not .jpg format file, though the link maps directly to the image.
![image](https://user-images.githubusercontent.com/75834609/127739747-1f1ca4de-5c58-4d3e-b124-7e2015566e1d.png)
