### ISSUE TITLE
Add onreact trigger type

### ISSUE THREAD

**Issue by michelhn** [jonas747/yagpdb#261]
Suggestion: Add onreact trigger type that takes 2 trigger forms
1st form: Message to watch required, message ID
2nd form: Emote to trigger optional

Variables to be passed:
User ID (who reacted/triggered)
Emote reacted (what emote was used)
React Count (for individual emotes)

Also trigger type onunreact would be good

How it would look like:
![unknown](https://user-images.githubusercontent.com/31596904/40881430-b946ddec-66c6-11e8-8932-ad019060a4cc.png)

suggestion by caskd

**Comment by casKd-dev** [comment]
Yup, would be really helpful!

**Comment by buthed010203** [comment]
I recommend that there is an "Events" trigger type category and under that there are things such as on react. on unreact, on role given / taken.

**Comment by Satty9361** [comment]
I think this is an issue which can be closed now with reaction triggers in custom commands. 
I also noticed that there are several obsolete issues. I can probably make a list unless you are no longer maintaining them. @jonas747 .

**Comment by jonas747** [comment]
go for it
