### ISSUE TITLE
Sometimes the reference of a user got from a command arg on custom commands is different

### ISSUE THREAD

**Issue by Lohkdesgds** [jonas747/yagpdb#266]
Just create a command like "-gimmeid" and put that code in:
```markdown
{{if eq (len .Args) 2}}
```{{(index .Args 1)}}```
{{end}}
```

Sometimes the reference got from a user is like "<@!XXXXXXXXXXXXXXXXXX>", sometimes it is "<@XXXXXXXXXXXXXXXXXX>".
Maybe it's because I'm on computer and my friend is on a phone? Why are they different?
Because of that, when I want to check an ID I have to do both ways. It's not that bad, but it should be fixed, right?

Is this a bug from Discord?

**Comment by jonas747** [comment]
not a bug, they're both valid, one is a nickname mention and the other is a username mention
what you could do instead is if you wanna get the id is do `{{(userArg (index .Args 1)).User.ID}}`
userArg will return a member object from a mention string like the above, you can only call it twice atm though in each custom command so beware of that

**Comment by Lohkdesgds** [comment]
Okay, that helps a lot
But still kinda buggy the way the arg is coming.

Hmm it won't work
The code I was writing is something like that:

```markdown
{{if eq (len .Args) 2}}{{$vary := index .Args 1}}
{{if eq $vary "-h"}}
Help text
{{else}}
Intro for the command
{{if or (eq $vary "<@!someonesid>") (eq $vary "<@someonesid>")}}
something
{{else if or (eq $vary "<@!someonesid2>") (eq $vary "<@someonesid2>")}}
something2
{{else if or (eq $vary "<@!someonesid3>") (eq $vary "<@someonesid3>")}}
something3
{{else}}
not registered.
{{end}}
{{end}}
{{end}}
```

I had to do that way because I didn't know another way atm. Changing the first line "{{$vary := index .Args 1}}" to "{{$vary := (userArg (index .Args 1)).User.ID}}" doesn't seems to work. Hmm.

Test code I used that failed too:

```markdown
{{if gt (len .Args) 1}}{{$vary := (userArg (index .Args 1)).User.ID}}{{$vary}}{{end}}
```

Both have the same error:
An error caused the execution of the custom command template to stop:
Failed executing template: template: :1:56: executing "" at <1>: can't evaluate field User in type *discordgo.User

**Comment by Lohkdesgds** [comment]
Okay, I got it. It's clean now. Thanks :3 
And that bug? <!code> and <code>? I don't think it's a problem for me anymore, but still being a bug.

**Comment by jonas747** [comment]
not a bug https://discordapp.com/developers/docs/reference#message-formatting
