### ISSUE TITLE
Reddit feed displays incorrectly

### ISSUE THREAD

**Issue by ErikHumphrey** [jonas747/yagpdb#273]
![](https://i.imgur.com/2RnlcD4.png)

Self-explanatory I hope. Please revert this change entirely.

**Comment by michelhn** [comment]
I just checked this. Seems to be working on the official YAGPDB server:
![image](https://user-images.githubusercontent.com/31596904/42164923-7c03eae4-7e07-11e8-8632-8c6b2950d427.png)

Seems to be working on my own server as well:
![image](https://user-images.githubusercontent.com/31596904/42165528-974e807e-7e08-11e8-8348-507d4e12ba60.png)

This issue can be closed.

**Comment by jonas747** [comment]
Make sure you allow the bot to use external emojis

**Comment by ErikHumphrey** [comment]
Also, just checked. The bot already had permission to use external emoji, but it still shows incorrectly.

**Comment by jonas747** [comment]
hm that's very strange, a toggle for the style could be added actually, yeah

see if i can get to it by the weekend
