### ISSUE TITLE
How to avoid timeout waiting for voice

### ISSUE THREAD

**Issue by lon9** [jonas747/yagpdb#284]
I'm making my own voice bot inspired by airhornbot using `bwmarrin/discordgo`. But there is a bug issued in that repo https://github.com/bwmarrin/discordgo/pull/426, so my bot is broken.
One day, I found your bot and it's working fine without the error, so I just want to know how to avoid that error in your bot. I just replaced `bwmarrin/discordgo` to yours `yagpdb` branch, but my bot is broken yet.  I'm not sure but people using that library may want to know that.
If you have time, tell me that please.

**Comment by jonas747** [comment]
i have basically rewritten the gateway implementation from scratch in my branch, that's one of the reasons things are different.

But this issue isn't really related to yagpdb, you should open an issue in the discordgo repo.

**Comment by FlameInTheDark** [comment]
Well, i dont know where a problem, but, i found strange solution
```go
vc, err := discord.ChannelVoiceJoin(guildID, channelID, properties.Muted, properties.Deafened)
	if err != nil {
		if _, ok := discord.VoiceConnections[guildID]; ok {
			vc = discord.VoiceConnections[guildID]
		} else {
			return nil, err
		}
	}
```
This works for my bot while I am looking for a normal solution.
