### ISSUE TITLE
If the server doesn't have a server avatar image the CP complains

### ISSUE THREAD

**Issue by michelhn** [jonas747/yagpdb#301]
![image](https://user-images.githubusercontent.com/31596904/44729157-807df480-aade-11e8-8023-439fd7f98449.png)
![image](https://user-images.githubusercontent.com/31596904/44729177-870c6c00-aade-11e8-945b-a3e57a2b8782.png)

**Comment by casKd-dev** [comment]
Maybe if there is a error on fetching the server avatar a placeholder could be loaded

**Comment by michelhn** [comment]
I'm not sure but I guess the same applies to people that don't have an avatar

**Comment by casKd-dev** [comment]
I think the best way to do this is to first fetch the head of the avatar to see if it is a 2xx response and if not then load the placeholder instead, and cache that avatar as well as the used method for a while. If the avatar returns a 200 then load that.
