### ISSUE TITLE
Editing old messages messes up logs

### ISSUE THREAD

**Issue by jonas747** [jonas747/yagpdb#304]

**Comment by casKd-dev** [comment]
Maybe keep original message in the logs and if its edited add by it the latest message.

**Comment by jonas747** [comment]
The issue was mainly that editing old messages after just starting up (having no message cache in that channel) adds that edited message to the cache, then when you use the logs command it will only fetch messages after that edited message.

This is fixed partially in https://github.com/jonas747/dstate/commit/de99db0ed9c70e712ef85845737a9c8cfbf56b93 as i was deleting all expired messages but 1, but its still an issue if you edit messages withing the 1h/12h cache duration.

The best solution i can think of is to always pull messages using the api when creating logs, then sort in the deleted messages from the cache.

**Comment by jonas747** [comment]
Fixed in https://github.com/jonas747/dstate/commit/74300d4abaf3f0ff7e9b70605cc7fd4182ca2e53 and https://github.com/jonas747/yagpdb/commit/f9825d110eca2e70421fd7345d0970a2183052ba

Edited messages whose original message is not already tracked in state is no longer added to the state, this should prevent all kinds of fuckery related to this
