### ISSUE TITLE
Role menu bug with new emotes

### ISSUE THREAD

**Issue by michelhn** [jonas747/yagpdb#318]
When setting up a rolemenu, YAG fails to add reactions of certain emojis, e.g. 👨‍❤️‍👨 or 👩‍❤️‍👩 (:couple_mm: / :couple_ww:). The menu still works, but if you want to use it yourself, it would remove the reaction fully so it would break the menu.
![image](https://user-images.githubusercontent.com/31596904/46099799-15e8d300-c1c8-11e8-8652-88f82223b1ca.png)

**Comment by jonas747** [comment]
Fixed in https://github.com/jonas747/discordgo/commit/700bab7217a1a81253282ca78c8a73a59b140c8b
