### ISSUE TITLE
New feature: Automod v2

### ISSUE THREAD

**Issue by jonas747** [jonas747/yagpdb#320]
Im currently working on automod v2, this will be a much more complex automod than the current one but will allow for much more flexibility in every place, i can also easily add features to it.

The current automod will be renamed to legacy, it will be kept around for a bit, but will probably be removed within a month, as maintaining 2 of these would be too much.

Quick design brainstorm:
 - Servers can create several rulesets
 - Rulesets contains sets of rules
 - Rules contains sets of `triggers`, `conditions` and `effects`
 - You should be able to toggle rulesets on with commands, so if you need to slow down a channel or a raid is happening you can employ very strict automod rules via a single command invocation

I've not decided on everything 100% yet, this is the 3rd or so "design" i've had, how punishments works, if they're just gonna be set up as normal rules, if there's gonna be multiple rules triggered at once, details like this i expect to figure out soon.

**Implementation status**

 - [x] Pretty up control panel
 - [x] Base bot logic
 - [x] Cache rulesets
 - [x] Stop infinite recursion with violation triggers
 - [x] Add limits or find another way to stop servers from using it to DOS the bot
 - [x] Add proper reason to actions
 - [x] User defined lists (words, websites etc): not started
 - [x] Base control panel work
 - [x] Log all triggered rules and make it available somewhere
 - [x] Make a message delete queue, so even in high spam scenarios it can keep up on a reasonable level

Rule part implementation status:

**Triggers:**
 - [x] x violations in x minutes
 - [x] Mentions
 - [x] Any links
 - [x] User specified website whitelisting/blacklisting
 - [x] User specified word whitelisting/blacklisting
 - [x] Regex * 
 - [x] x messages in x seconds
 - [x] x mentions in a channel in x seconds (channel and user based?)
 - [x] Similar messages (spam) per user *
 - [x] All caps
 - [x] Nickname - whitelisted/words*
 - [x] Nickname regex*
 - [x] Google safebrowsing
 - [x] Server invites
 - [x] Parse away markdown in banned words

*: undecided on

**Conditions:**
 - [x] Role whitelist/blacklist
 - [x] Channel blacklist/whitelist
 - [x] Channel category blacklist/whitelist
 - [x] User account age
 - [x] Member join age

**Effects:**
- [x] +Violation
- [x] Delete message
- [x] Kick user
- [x] Ban user
- [x] Mute user
- [x] Warnings
- [x] Set nickname

**Comment by buthed010203** [comment]
ALL CAPS MESSAGE DETECTION: set a custom threashhold for % of message in caps

**Comment by buthed010203** [comment]
Repeated messages so people dont send the same message over and over (similar to what automod bot "vortex" has)

**Comment by buthed010203** [comment]
I doubt this is possible but zalgo / weird text removal?

**Comment by buthed010203** [comment]
Nickname dehoisting (also maybe have a nickname detector that removes invite links or whatever)

**Comment by buthed010203** [comment]
Join trigger so you can kick new accts easy

**Comment by buthed010203** [comment]
Add role effect type
