### ISSUE TITLE
Allow reputation +'s and -'s to be logged like kicks and mutes.

### ISSUE THREAD

**Issue by slyguy65** [jonas747/yagpdb#323]
So I am playing around with what I can use from discord bots and the rep thing is a good idea.

But without the proper logging I can't see who may or may not be spamming rep. Can we get a logging feature like moderation powers do like how you can have warnings and mutes and stuff auto log the action to a channel "for the record" a way to do that for rep would be nice too.

**Comment by buthed010203** [comment]
Good idea, for now you can always use a custom command to send a message to a channel though.

**Comment by jonas747** [comment]
I actually do log them all already, i just haven't made any way to access those logs

**Comment by jonas747** [comment]
done with https://github.com/jonas747/yagpdb/commit/0f06cb7046a62dea25d5846f9badf8cc0aa0a6d1 and https://github.com/jonas747/yagpdb/commit/52a5867534caa30b95f963051bca3d5155e0c8a2
