### ISSUE TITLE
Dynamic role recognition for rep?

### ISSUE THREAD

**Issue by slyguy65** [jonas747/yagpdb#325]
This is a suggestion.

Can we have multiple roles allowed for certain things. Example the mute and kick lets you make a list of allowed roles. While others such as rep moderation is restricted to only 1 role for admin and 1 role for give/take. I know you can just make a dedicated role for this but was just wondering how much of a hassle doing it the list way would be.

**Comment by jonas747** [comment]
It's relatively simple, its something that is relatively simple but will require me to update the database, so i have put it off for a while.

**Comment by jonas747** [comment]
Done in 4ded4d458d3ab55ace2d0352a35ae87b7f7f82fb
