### ISSUE TITLE
Auto role questions/suggestions

### ISSUE THREAD

**Issue by slyguy65** [jonas747/yagpdb#326]
Ok so I can't seem to find any mainstream discord bot that allows for really deep auto role functionality. They are ALL based on time, I think I saw one based on number of messages sent. But I can't find it again.

The issue with time based auto role is that discord doesn't recognize time spent on that SERVER. You can join the server and just "idle" there essentially while having discord open and bam, autorole that bitch. So I guess if you can add a # of messages needed rather than just time, that would be nice. If there is any other way to "gauge" peoples activity that can be tracked with auto role it would be nice to have something other than just time since its way to general.
Case in point I made a "regulars" roles and I want people to be able to gain it automatically based on something like time spent on SOLELY my discord/discord tab whether its browsing chatting whatever. But it doesn't work like that, so oh well. That is on discord to implement that sort of recognition I assume. 
So # of messages + time would be nice rather than either or.

Another sort of "auto" role thing I see and was wondering if it could be implemented in the control panel was using emojis as a -role example role. If you been to any big discords you know what I am talking about, where you can select your region by clicking an emoji and it auto roles you into the role based on that region (i.e clicks NA region emoji gets NA role).

Anyway I don't know of any mainstream bots that have this on their control panel so if there was a way to add that into base line functionality that would be AWESOME. 

I actually have it on my server right now, but the guy who made it is never really on anymore and the way to set it up was quite clunky, so I ask you, a mainstream bot dev if it is possible to implement in a bot that has a control panel.

**Comment by buthed010203** [comment]
Bots like Mee6 and Tatsumaki have level/xp roles which is similar.

**Comment by buthed010203** [comment]
Also theres the rolemenu which we have that does the role reaction stuff...

**Comment by slyguy65** [comment]
elaborate on this rolemenu?

**Comment by slyguy65** [comment]
> 
> 
> Bots like Mee6 and Tatsumaki have level/xp roles which is similar.
> 
> Also Unbelievaboat has a shop and currency system which can allow you to buy roles etc...

Which one would you recommend?

**Comment by buthed010203** [comment]
Heres a rolemenu that I have in my server for example https://imgur.com/a/g0Lue7o
You can set it up under the role commands area on the cp

In terms of the bot, the easiest to use and most popular bot would for sure be mee6 but the other 2 are great alternatives.

**Comment by buthed010203** [comment]
You would yeah, you could just make one message and call it games though
