### ISSUE TITLE
banned words to prevent -sb spam not working?

### ISSUE THREAD

**Issue by slyguy65** [jonas747/yagpdb#327]
I am trying to limit certain soundboard sounds and none of the banned words are woking, I tried with and without the -sb the word is "scpspook" and not matter what it doesn't auto mute or anything for people who say it. Any help?

**Comment by jonas747** [comment]
I'm not sure what you're doing, please be more specific, are you trying to limit certain sounds to certain people? if so you can already restrict sounds to a role

**Comment by buthed010203** [comment]
@jonas747 Hes trying to make the sb a banned word so that theres a cooldown as currently there are no cooldowns...

**Comment by slyguy65** [comment]
Yes, I was trying to limit certain sounds in a way that can't be abused, and I don't like clutter so I was just going to make certain sound board commands "banned" words. But for some reason the banned words option doesn't seem to be working at all.

**Comment by slyguy65** [comment]
Damn it doesn't work the way i intended. It auto deletes the word without it following the command first...so I can't use it as a way to moderate usage of more extreme soundboard sounds...sigh.

**Comment by jonas747** [comment]
yeah commands wont be  triggered on messages that also triggers automod, there is no simple solution for this

**Comment by slyguy65** [comment]
ah commands wont be triggered on messages that also triggers automod, there is no simple solution for this
