### ISSUE TITLE
Anyway to limit/moderate/turn off soundboard?

### ISSUE THREAD

**Issue by slyguy65** [jonas747/yagpdb#332]
I am sure there is a custom way to do it and if there is please let me know.

So I am currently looking to moderate/limit soundboard.
I know I could just make ANOTHER soundboard role with the more spammy or obnoxious sounds but that seems like a bit much, especially considering it would be too much micromanaging. So I was wondering if there was a way to tweak "banned" words so as to add a "warning" system to it.

So maybe have it under "warnings" allow us to make a list of words that "warn" the person saying them and muting them after repeat offenses? So if I ban the word "mud" and they say it, it stays in chat, but they get a "warning" but if they say it again they get muted. That way we can moderate commands in a way. Like sound board or rep. Or any other command really.

If that is too much, can we get a simple -stop command? That stops the bot from doing whatever its doing? i.e playing soundboard or any other ongoing processes it can do? 

Cause I added a 3 minute long sound to the sound board, and its good, but if someone does it more than once in the span of well 5 minutes, its just annoying. And there is NO way to even undo it except moving the bot out of channel and letting it finish elsewhere.

**Comment by buthed010203** [comment]
If Jonas ever adds cooldowns to custom commands this would be easy, I’ve wanted cooldowns for ages now tho.

**Comment by buthed010203** [comment]
@jonas747 since cooldowns are possible this can be closed
