### ISSUE TITLE
Bot Not Responsive 

### ISSUE THREAD

**Issue by aprilkitty** [jonas747/yagpdb#347]
I'm currently setting up a rolemenu on my server. I have created a group and the roles, etc. However, whenever I use any command within the server, the bot does not respond. It is quite frustrating. Any way to fix this?

**Comment by CHamburr** [comment]
DM me: CHamburr#2591

**Comment by aprilkitty** [comment]
^ It won't allow to me without being in a server with you, or being friends with you on Discord. oof.

**Comment by CHamburr** [comment]
Send a friend request. .

**Comment by sheeeev66** [comment]
I am having the same problem... can you please tell me the solution? my discord is Sheeeev66#0321 thank you!
