### ISSUE TITLE
[SUGGESTION] Wait Variable/Function for Custom Commands

### ISSUE THREAD

**Issue by captahbvious** [jonas747/yagpdb#363]

**Comment by captahbvious** [comment]
Pretty much says it all in the title. A wait function for the Custom Commands that would allow us to create a delay in the command to force a timed output (i.e. a temporary role)

{{wait 30s/h/d}}

I am going to assume you have thought of this and might have found issues in how it handles all these waits and the drain on the server hardware, so if you can't do this, I would understand. But the things we could do with this function... is amazing.

**Comment by buthed010203** [comment]
I already suggested this ages ago :p

**Comment by jonas747** [comment]
Not likely to be added, as i can't restore the state of it after shutting down the bot.

An alternative is to add something like `{{execCC delay-seconds cc-id data}}` instead

**Comment by buthed010203** [comment]
Damn, I have wanted this for so long and it would be so good in so many ccs I use

**Comment by buthed010203** [comment]
@jonas747 this can be closed as its now possible
