### ISSUE TITLE
[SUGGESTION] Add Support For a Counter Variable (REPUTATION)

### ISSUE THREAD

**Issue by EliteXSkill** [jonas747/yagpdb#378]
Please add support for a counter variable into the bot's custom syntax.

Specifically, we want to implement system for limiting a user to +rep another user once.
It's a problem in a very large server like ours that we run, do you know if there is any system for that to be implemented?

I think something like a counter would be the only way to measure that, but if there is any other way you can implemenet that Id'e love to hear it. Thanks!

**Comment by buthed010203** [comment]
@jonas747 Can be closed as its now doable using db
