### ISSUE TITLE
Command to manually add/remove roles from other users

### ISSUE THREAD

**Issue by FunnyMan3595** [jonas747/yagpdb#411]
Discord's permissions sadly force you to grant the "Manage Roles" permission if you want to give someone the ability to add and remove roles from other people.  This permission is much broader than simple role management, and includes the ability to edit role permissions and and outright delete roles.  It's useful for moderators to be able to assign utility roles (regular, member, etc.), but giving them Manage Roles is overkill.

One solution would be to have a command that allows members of one role (Moderator or similar) to be able to add and remove specified lesser roles from any user.

**Comment by jonas747** [comment]
Implemented
