### ISSUE TITLE
[Suggestion] Deny usage of inventory item when amount entered exceeds amount held.

### ISSUE THREAD

**Issue by Sparklepaws** [jonas747/yagpdb#413]
After some testing I discovered that the bot allows users to "use" higher amounts of items than they currently hold; the actual amount used is ALL of the held item. 

For example:
UserOne has **40 Cookies** in their inventory. They use the command "**use-item 50 Cookies**". Rather than alerting them that they don't own that amount, the bot simply takes all of their item.

This becomes problematic if moderators want to create shop items for purposes other than role assignment since it essentially leaves no trace of the actual amount contained within the user's inventory before consumption. Thus to any onlookers it appears as though UserOne has indeed used **50 cookies**, not **40**.

**Comment by buthed010203** [comment]
I think you've got the wrong bot...

**Comment by Sparklepaws** [comment]
> 
> 
> I think you've got the wrong bot...

You're absolutely right, I had several pages open. My bad.
