### ISSUE TITLE
YAGPDB.xyz blocked messages

### ISSUE THREAD

**Issue by survivor303** [jonas747/yagpdb#419]
I dont know where to ask about this because i cannot use support server yet (eh).

So i actived Youtube upload feeds from notification and it works but channel where i want to send them (my own server/channel) keep blocking these messages and people need to click the message for open it.

Is that a bug on discord, yagpdb bot or my settings?

I dont have anything else on that bot than just youtube feed announces.

Sorry if this is wrong place to ask, but i really dosnt understand why people cannot ask questions in the yagpdb _support_ server right away?

**Comment by ACA30** [comment]
To speak in the support server, you would need to go to the #faq-read-me-first channel and click the emoji at the bottom, indicating that you have read the faq. This will allow you to speak in #help.

**Comment by jonas747** [comment]
You seem to be contradicting yourself, how can they click on the messages if the bot is blocked from sending messages?

**Comment by buthed010203** [comment]
@jonas747 dead thread, close?
