### ISSUE TITLE
Unable to update role menu with new roles

### ISSUE THREAD

**Issue by Majestano** [jonas747/yagpdb#452]
I've been editing my role menus and updating them with some new roles that we've made over time but the bot keeps hanging up, stating that someone's currently editing the role menu when I react with the emote to assign the new role when updating the role menu. It still happens even if I've moved to a new menu in the editor, pressed save on every role and close the window entirely. The bot also seems to repost that message after some time when the role menu is finished but does nothing if I wait a similar amount of time while it's open

Reproduction:
Add a new role to a role menu (only added roles to multi role sets)
Run the -rolemenu update [Message ID] command
React with the emoji you want to use for the prompted role

![image](https://user-images.githubusercontent.com/50759678/57963514-34d0dc80-78f3-11e9-8d2a-edaa52af1c7e.png)

**Comment by emorell96** [comment]
Hi,
I have exactly the same problem on my discord. I cannot update the role. Nor can I cancel the command. Is there something I can do about it? I'd like to fix it or at least cancel the command. Thanks.

**Comment by Victor-Bo** [comment]
To cancel the command, just delete all the messages you don't need anymore : the menu message, the message with your command and the message of the setup
