### ISSUE TITLE
Why can't access the verify role on verification system...

### ISSUE THREAD

**Issue by JerryTheBoy** [jonas747/yagpdb#470]
I Can't access the verify role on verification system ![Screenshot_20190702-012534](https://user-images.githubusercontent.com/36040971/60455170-55b57d00-9c68-11e9-93b3-6fb1a3b96d05.png)

**Comment by lyonhaert** [comment]
You need to go to Server Setting > Roles, then move the YAGPD.xyz role higher (probably just under Admin, above Moderator).
