### ISSUE TITLE
dbSet function does not limit key to 256 chars

### ISSUE THREAD

**Issue by AlbertoMonteiro** [jonas747/yagpdb#477]
In this code, there is no string limitation to 256 chars on key value
https://github.com/jonas747/yagpdb/blob/105524561083b81da3559b48e4a116d5358b58d9/customcommands/tmplextensions.go#L347-L362

All other db methods do 
```go
keyStr := limitString(templates.ToString(key), 256)
```

**Comment by jonas747** [comment]
fixed in https://github.com/jonas747/yagpdb/commit/eb883c8ec49de56f52f7ef8494725e84964125f0
