### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by HeberonYT** [jonas747/yagpdb#482]
I am using the custom commands, but I want the message to include the mention of the user that caused the command to fire (@HeberonYT), but I can't find the right way to make it work.
![Screenshot_10](https://user-images.githubusercontent.com/13698597/62754922-74f9b400-ba37-11e9-93ae-2dc721a3271b.png)

**Comment by buthed010203** [comment]
`{{.User.Mention}}` if you havent figured it out yet

**Comment by HeberonYT** [comment]
@buthed010203 Thanks for your answer, but it doesn't work. The result is as follows:
![Screenshot_1](https://user-images.githubusercontent.com/13698597/63304007-21912c80-c2a7-11e9-8828-a714d243d0c1.png)

**Comment by buthed010203** [comment]
You cant mention people in the title field of embeds

**Comment by HeberonYT** [comment]
@buthed010203 that explains everything. Thanks for the help.
