### ISSUE TITLE
Very late or missing YouTube announcements

### ISSUE THREAD

**Issue by Skullmonkey** [jonas747/yagpdb#487]
I have 6 channels monitored. (3 of them are test channels that upload every day.) I see in the [docs](https://docs.yagpdb.xyz/notifications-and-feeds/youtube-feed) that it can take from 5-15 minutes to post an announcement. I am finding that it is posting anywhere from 2-5 hours after the upload to YouTube if it posts at all. I get that the bot is widely used and server loads can spike if it was a one off deal every once and a while but this seems to be consistent.

**Comment by jonas747** [comment]
The youtube api in general is just unreliable and limited, other bots such as mee6 have the same problems.

**Comment by Skullmonkey** [comment]
Fair enough. It's beyond your control so I will go ahead and close this.
