### ISSUE TITLE
Rep Leaderboard Command

### ISSUE THREAD

**Issue by fadedboiii** [jonas747/yagpdb#505]
Users should be able to do a command to make the rep leaderboard show in the discord chat.

**Comment by LilTrublMakr** [comment]
Try `toprep`?
![Annotation 2019-09-08 170201](https://user-images.githubusercontent.com/54646041/64494407-6848c580-d25a-11e9-8dd6-a9002d05cd09.png)

**Comment by buthed010203** [comment]
Yeah this is already possible using toprep. @fadedboiii pls close this.

**Comment by noahggarrett** [comment]
I agree this would be very usefull

**Comment by noahggarrett** [comment]
why did you close this I loved the idea

**Comment by LilTrublMakr** [comment]
Because there is already a command to do this: `-toprep`

**Comment by buthed010203** [comment]
^

Read the comments before commenting yourself
