### ISSUE TITLE
Suggestion: Log the last x messages

### ISSUE THREAD

**Issue by LilTrublMakr** [jonas747/yagpdb#511]
Just a suggestion to modify the log command for users to only log the last x amount of messages from the current channel while defaulting to the current default.

EX:
-log 10   < Log the last 10 messages only with a maximum of the current default
-log        < Logs the current default (runs as currently does)

**Comment by noahggarrett** [comment]
already done unless I misunderstand what you are saying

**Comment by LilTrublMakr** [comment]
Indeed you can. I realize that I was not using a space to try it. (It was a long bad day lol)
