### ISSUE TITLE
Auto Moderator v2 does not set nicknames.

### ISSUE THREAD

**Issue by themousery** [jonas747/yagpdb#517]
On my Discord server, I have an automoderator v2 rule set up so that if a user puts a derogatory word in their nickname, the bot will warn them and reset their nickname. It warns the user just fine, but it does not reset the nickname like it should.

**Comment by buthed010203** [comment]
Are you sure the bot has the change nickname permission and its highest role is above that of the user whos name its changing?

**Comment by themousery** [comment]
Yes. The YAGPDB.xyz role (which I double checked is given to the bot itself) is given a lot of permissions, including ‘administrator’ and ‘manage roles’. 

I even tried experimenting with having different rules set the nickname - and they do nothing to the nickname.

**Comment by buthed010203** [comment]
And the bots role is above said users highest role in the role list?

**Comment by themousery** [comment]
Yes - I should have mentioned that. The YAGPDB.xyz role is the highest role on the server. It’s above all other roles on the list.

**Comment by buthed010203** [comment]
Whats the server id?

**Comment by themousery** [comment]
Wow - I just figured it out. I was testing it on myself - the owner - and it can’t change the owner’s nickname. It works fine on everybody else. I should have thought of that before 😅. Thank you for the willingness to help!! :)

**Comment by buthed010203** [comment]
Haha, no problem man, have a good day.

(Also close the issue if you dont mind).
