### ISSUE TITLE
Suggestion: noun function

### ISSUE THREAD

**Issue by iansannar** [jonas747/yagpdb#521]
Currently there is an [`adjective`](https://docs.yagpdb.xyz/reference/templates#miscellaneous) function that returns a random adjective. A `noun` function that returns a random noun would be fun.

Looking at [`/common/adjectives.go`](https://github.com/jonas747/yagpdb/blob/master/common/adjectives.go), this looks pretty simple and I could easily create such a file for nouns. I suspect there's more to implementing a function than creating a file, though (I'm not familiar with Go, JS, or YAGPDB internals), so I think I'll poke around a bit in the source before making a PR.

**Comment by jonas747** [comment]
https://github.com/jonas747/yagpdb/blob/master/common/templates/context.go#L64
and https://github.com/jonas747/yagpdb/blob/master/common/util.go#L103 are the bits, pretty simple stuff.

**Comment by iansannar** [comment]
https://github.com/jonas747/yagpdb/pull/630
