### ISSUE TITLE
sampleenvfile

### ISSUE THREAD

**Issue by veretajaht** [jonas747/yagpdb#530]
Hi. How is this file, the variables presented to system. Entries have no export, but it has bash - so should be shell related still. 
Or do I have to add that export and then append this all to ~/.bashrc?

Could you explain this maybe in the readme or here. thank you1

**Comment by jonas747** [comment]
They're environment variables, how you set them depends on the system you're using, that file is merely an example setup.

If you can't figure this part out you should not even bother trying to run the bot, its complicated to run, especially if you lack a understanding of basics such as environment variables.
