### ISSUE TITLE
automod word blacklist not triggering on partial matches

### ISSUE THREAD

**Issue by NaniteFactory** [jonas747/yagpdb#544]
currently `Word blacklist` triggers only on messages that contain the whole exact word matching one in the specified list, that makes it very easy to bypass
please make it so then the automod also does partial matches

**Comment by buthed010203** [comment]
Its a word blacklist not a partial word blacklist...
time to start matching every word that contains the letter `a`
i dont see why you dont use regex instead?

**Comment by NaniteFactory** [comment]
`Message matches regex` doesn't allow to add a list of multiple regular expressions. I would have to add and click it for every each banned word when I have like hundreds of swears on my list..

It would be nice to have another option in `Word blacklist` like this:
- Word blacklist (Match any part of the word)
- Word blacklist (Match exact word only)

**Comment by buthed010203** [comment]
> Match any part of the word
So you will just delete any message that contains a-z and A-Z? Cool

**Comment by NaniteFactory** [comment]
closing this, since we can just create a custom command with trigger regex `.*` and implement what's shown above
