### ISSUE TITLE
Bot doesn't respond to commands with discord emotes

### ISSUE THREAD

**Issue by Mnky313** [jonas747/yagpdb#551]
If I create a custom command that should respond to anything that contains :regional_indicator_n: for example, if someone sends the emote for :regional_indicator_n: it will not respond, I tried with just the text and no colons (regional_indicator_n) as well, same result
![image](https://user-images.githubusercontent.com/23646586/68532505-f3424c80-02eb-11ea-9c48-cd3642e7f080.png)
![image](https://user-images.githubusercontent.com/23646586/68532510-fdfce180-02eb-11ea-9873-ea1dff6d00e1.png)

**Comment by Satty9361** [comment]
Use unicode versions of the emojis. It works just as expected. @Mnky313 
![Capture1](https://user-images.githubusercontent.com/56998894/68532738-67e3ae00-0321-11ea-827b-6098e21a2b36.PNG)
![Capture2](https://user-images.githubusercontent.com/56998894/68532761-8d70b780-0321-11ea-8e08-bc937ec64c36.PNG)

**Comment by Mnky313** [comment]
> Use unicode versions of the emojis. It works just as expected. @Mnky313
> ![Capture1](https://user-images.githubusercontent.com/56998894/68532738-67e3ae00-0321-11ea-827b-6098e21a2b36.PNG)
> ![Capture2](https://user-images.githubusercontent.com/56998894/68532761-8d70b780-0321-11ea-8e08-bc937ec64c36.PNG)

Ok, that works.
