### ISSUE TITLE
Dockerfile broken

### ISSUE THREAD

**Issue by Gibby** [jonas747/yagpdb#655]
Cloned the repo and ran `docker build` inside of the yagpdb_docker directory. It gives the following error.

> get "golang.org/x/oauth2/google": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at //golang.org/x/oauth2/google?go-get=1
get "golang.org/x/oauth2/google": verifying non-authoritative meta tag
get "cloud.google.com/go/compute/metadata": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at //cloud.google.com/go/compute/metadata?go-get=1
get "cloud.google.com/go/compute/metadata": verifying non-authoritative meta tag
cloud.google.com/go (download)
get "google.golang.org/api/googleapi": found meta tag get.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at //google.golang.org/api/googleapi?go-get=1
get "google.golang.org/api/googleapi": verifying non-authoritative meta tag
google.golang.org/api (download)
get "google.golang.org/api/youtube/v3": found meta tag get.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at //google.golang.org/api/youtube/v3?go-get=1
get "google.golang.org/api/youtube/v3": verifying non-authoritative meta tag
github.com/googleapis/gax-go (download)
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc?go-get=1
google.golang.org/grpc (download)
github.com/golang/protobuf (download)
get "google.golang.org/grpc/codes": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/codes?go-get=1
get "google.golang.org/grpc/codes": verifying non-authoritative meta tag
get "google.golang.org/grpc/status": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/status?go-get=1
get "google.golang.org/grpc/status": verifying non-authoritative meta tag
get "google.golang.org/genproto/googleapis/rpc/status": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at //google.golang.org/genproto/googleapis/rpc/status?go-get=1
get "google.golang.org/genproto/googleapis/rpc/status": verifying non-authoritative meta tag
google.golang.org/genproto (download)
get "go.opencensus.io/plugin/ochttp": found meta tag get.metaImport{Prefix:"go.opencensus.io", VCS:"git", RepoRoot:"https://github.com/census-instrumentation/opencensus-go"} at //go.opencensus.io/plugin/ochttp?go-get=1
get "go.opencensus.io/plugin/ochttp": verifying non-authoritative meta tag
go.opencensus.io (download)
get "go.opencensus.io/trace": found meta tag get.metaImport{Prefix:"go.opencensus.io", VCS:"git", RepoRoot:"https://github.com/census-instrumentation/opencensus-go"} at //go.opencensus.io/trace?go-get=1
get "go.opencensus.io/trace": verifying non-authoritative meta tag
github.com/golang/groupcache (download)
get "go.opencensus.io/trace/propagation": found meta tag get.metaImport{Prefix:"go.opencensus.io", VCS:"git", RepoRoot:"https://github.com/census-instrumentation/opencensus-go"} at //go.opencensus.io/trace/propagation?go-get=1
get "go.opencensus.io/trace/propagation": verifying non-authoritative meta tag
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go get -v   github.com/jonas747/yagpdb/cmd/yagpdb' returned a non-zero code: 1

**Comment by maidos** [comment]
having the same exact issue. Any fix?

**Comment by jonas747** [comment]
This should be fixed now, make sure to pass the "--pull" argument to make sure you pull the latest go version.
