### ISSUE TITLE
-settimezone -d does not work

### ISSUE THREAD

**Issue by Subbarker** [jonas747/yagpdb#693]
eom

```
-tzset -d
-tzset -u
YAGPDB.xyz:
Your current time zone is registered to: America/New_York EDT (UTC-4)
```

**Comment by jonas747** [comment]
Is it still not working?

**Comment by Subbarker** [comment]
It's working now, though I just copied the same command with c+p

**Comment by C0braD3v** [comment]
Seems this issue is no longer occurring for @Subbarker and I also am unable to reproduce. Can this issue be closed?
