### ISSUE TITLE
Emoji not updating after a role removed.

### ISSUE THREAD

**Issue by djlax805** [jonas747/yagpdb#705]
Hello, could be on my setup. I followed the color guide setup and while the roles are being removed when another is selected (as expected), the counter on the emoji is not being reduced by one (the role that was auto-removed for that role).

I would expect both the roles to be switched and the emoji counters.

**Comment by Satty9361** [comment]
This automatic removal of reaction feature has been made Premium ONLY due to discord ratelimits. The actual role removal is handled as expected. You are also able to manually code this effect via custom commands. I would suggest visiting the Support Server for further assistance.

**Comment by djlax805** [comment]
Sounds good thanks for the info - looks like there is an updated video that covers some of the new behaviors you mentioned. https://www.youtube.com/watch?v=IaTfJ4vqHhc
