### ISSUE TITLE
how to disable ssl ?

### ISSUE THREAD

**Issue by AkgunFatih** [jonas747/yagpdb#711]
i am getting this error 
`ERRO http: TLS handshake error from [::1]:40036: acme/autocert: server name component count invalid  stck="http.(*Server).logf:server.go:3061"`

because i don't need SSL as i am not sharing my ip to the world

pls dont just close this because i dont know how

**Comment by realdeadbeef** [comment]
Ayo, I wanna know how to disable ssl too!

**Comment by 3kh0** [comment]
me too!

**Comment by shams-mac-m1** [comment]
me too
