### ISSUE TITLE
[Bug] Rolemenu "rr" setting

### ISSUE THREAD

**Issue by MicaelJarniac** [jonas747/yagpdb#718]
I've noticed that, when a role menu is created with `rr = false`, meaning that removing the reaction shouldn't remove the role, if the user removes the reaction then adds it again, it acts as if `rr = true` and they had removed the reaction.

So basically, instead of `rr = false` completely disabling the removal of the role, it just makes it so that the bot ignores the removal of reactions, but when reacting again, it triggers the same logic as if the reaction was removed.

I'm not quite sure if it's really what is going on, nor if it's accidental or a feature, but I decided it's worth opening an issue here anyways.

**Comment by Satty9361** [comment]
That how it works. rr = true means one click -> removal
rr= false mans 2 clicks -> removal
to disable removal of roles use require one role at one times in case of single and minumum roles in case of multiple mode

**Comment by MicaelJarniac** [comment]
You're fast. I was just digging in the documentation and literally came back here to correct myself.

> Do NOT set the require role to the role you are assigning. You generally will not want to set the ignore role to the role you are assigning either unless you wish to prevent the user from removing that role through the role-menu.
