### ISSUE TITLE
(Bug) Reaction Role not working! 🙉

### ISSUE THREAD

**Issue by TheAresjej** [jonas747/yagpdb#727]
**Bug**: The bot is completely unresponsive to the command

![image](https://user-images.githubusercontent.com/19390797/82821728-e14d8300-9ea4-11ea-9cc1-51223112f047.png)
![image](https://user-images.githubusercontent.com/19390797/82821742-e7436400-9ea4-11ea-9d42-4a108fae6ffa.png)
![image](https://user-images.githubusercontent.com/19390797/82821799-ff1ae800-9ea4-11ea-9178-651aebd26a80.png)
![image](https://user-images.githubusercontent.com/19390797/82821880-270a4b80-9ea5-11ea-8b4f-f05f7fa135a4.png)

**Comment by Satty9361** [comment]
There are several reasons for this to happen. I suggest joining the support server so that we can look further into it and see if it is indeed a bug or incorrect setup issue.
