### ISSUE TITLE
Suggestion:  Mute also prevents adding reactions (maybe as an optional toggle?)

### ISSUE THREAD

**Issue by gatherer818** [jonas747/yagpdb#767]
I don't think this has been suggested yet.  Muted someone for harassing another player about their decisions, they started reacted to all that player's messages in the game chat with emotes anyone could interpret as continuing to call them an idiot.  I manually removed reactions from the mute role in that channel, but doing it for every channel would take quite a while, it'd be great if YAGPDB could do that automatically.

**Comment by Satty9361** [comment]
This is already an option under  Moderation  -> Mute : 
"Disallow Adding Reactions when muted"

**Comment by gatherer818** [comment]
I swear I checked, I'm just blind, thank you.  I found it.
