### ISSUE TITLE
error message given when a user reacts to things in the server, custom commands for ticket system

### ISSUE THREAD

**Issue by sasukouchiha** [jonas747/yagpdb#777]
We keep getting error messages when a user or bot uses a reaction to any message, not trying to make a ticket.  Please help.

![yagpdb error2](https://user-images.githubusercontent.com/48902541/92191378-a3f87a00-ee31-11ea-9bab-eb1596ee3be9.png)

![yagpdb error](https://user-images.githubusercontent.com/48902541/92191313-73184500-ee31-11ea-98a0-27ceb12a231b.png)

**Comment by Pedro-Pessoa** [comment]
That's not an issue with the bot but an error with a CC of yours. Ask for help in the support server.
