### ISSUE TITLE
-weather moon command shows something weird

### ISSUE THREAD

**Issue by Cooliokid956** [jonas747/yagpdb#791]
when i type in `-weather moon`, this appears:
```
                 .    
             .    
          .    
       .    
      /    
    .    
   /    
```
what is this? is it an easter egg?

**Comment by Jo3-L** [comment]
Looks like the formatting messed up - it originally showed the current phase of the moon, if I recall correctly. In any case, this easter egg is not added by us, but rather [wttr.in](https://wttr.in), the API we use for the `weather` command.

**Comment by Cooliokid956** [comment]
Hmm, well it was pretty interesting anyways
