### ISSUE TITLE
Question: How do I make yagpdb add a reaction to a message using a cc?

### ISSUE THREAD

**Issue by Xag8031** [jonas747/yagpdb#811]
I am sorry if this is stupid but I cant find a way to do this

**Comment by MatiasMFM2001** [comment]
[Read the docs](https://docs.yagpdb.xyz/reference/templates#message-functions). If you still have trouble, join [YAG's support server](https://discord.com/invite/99JvyMsw9h)! We can help you in **#custom-command-help**

**Comment by Xag8031** [comment]
Thanks!
