### ISSUE TITLE
Slash Commands Support

### ISSUE THREAD

**Issue by maltejur** [jonas747/yagpdb#819]
The new discord slash commands feature would be pretty nice for the bot. It gives a preview of all available bot commands.
https://discord.com/developers/docs/interactions/slash-commands
![Screenshot 2020-12-22 115001](https://user-images.githubusercontent.com/48161361/102880591-de6f3c80-444b-11eb-8043-39617e191326.png)

**Comment by JordiHakimZiyech** [comment]
I'm sure jonas will look into it, but the bot is in a feature freeze at the moment

**Comment by PlavorSeol** [comment]
This can now be closed as #878 was merged.
