### ISSUE TITLE
Unknown Message wtf?

### ISSUE THREAD

**Issue by ZeroCool22** [jonas747/yagpdb#821]
When i try to use a -m id y always get the damn **Unknown Message**!

Command i' m trying:

**-rolemenu create Plataform -nodm -m 748700846384218143**

**The bot was not able to perform the action, discord responded with: Unknown Message**

**Comment by JordiHakimZiyech** [comment]
please use the support server for these issues.
but as the error says, the message id is invalid

**Comment by ZeroCool22** [comment]
OK, thx.
