### ISSUE TITLE
Remove Added Role Message

### ISSUE THREAD

**Issue by RobHowdle** [jonas747/yagpdb#822]
Hello! First time contributing here, I did have a quick check but I may have missed it, I couldn't seem to find a way to turn off the private message from the bot alerting you that you have added a role. Within my server members can add multiple roles to for them to receive multiple messages from the bot can be quite annoying for some. Is there a way to turn off this message? 

Thanks!
Rob

**Comment by Olde7325** [comment]
You can do that using the `-nodm` flag, as stated in the documentation, e.g:
`-rolemenu create <groupname> -nodm`. 
This will still DM error messages, but disable confirmation DMs.

---
Next time, please use [the support server](https://discord.com/invite/0vYlUK2XBKldPSMY), thanks in advance!

**Comment by RobHowdle** [comment]
My apologies I had completely missed that part of the documentation entirely (rookie mistake) Thank you very much for the assistance there!
