### ISSUE TITLE
Tickets: View only perms

### ISSUE THREAD

**Issue by Nicholas6506** [jonas747/yagpdb#841]
On the Tickets menu of the YAGPDB Control panel
Under the category where you can select: Role(s) for people considered mods (tickets can be set to an admin only mode)
Add a category for: Role(s) for people considered staff (View only)
This would allow for staff members to view the tickets but not message in them

**Comment by JordiHakimZiyech** [comment]
please do not spam across github and discord server. suggestions should stay in the discord server

**Comment by Nicholas6506** [comment]
ok / sorry it says on discord that you can add suggestions here as well that's why i did

**Comment by TheHDCrafter** [comment]
> ok / sorry it says on discord that you can add suggestions here as well that's why i did

Where exactly does it say that? (I am just asking so i can edit or ask jonas to edit the part that states you can suggest stuff via github)

**Comment by l-zeuch** [comment]
> > ok / sorry it says on discord that you can add suggestions here as well that's why i did
>
> Where exactly does it say that? (I am just asking so i can edit or ask jonas to edit the part that states you can suggest stuff via github)

It is stated in the channel topic of #suggestions: 
![channel topic](https://cdn.discordapp.com/attachments/476178740133494784/809031340707807272/unknown.png)

**Comment by TheHDCrafter** [comment]
Thanks, I edited the channel topic and remove the GitHub part :)
Am 10. Feb. 2021, 13:02 +0100 schrieb Luca Z. <notifications@github.com>:
