### ISSUE TITLE
Role Commands: "You don't have a required role for this self-assignable role group."

### ISSUE THREAD

**Issue by jahinzee** [jonas747/yagpdb#844]
Hello all,

I am trying to create role assignment menus, however when I try to self-assign any role, I get this message:
![image](https://user-images.githubusercontent.com/56011682/109376802-18146600-791b-11eb-9fc3-5860f40f12cb.png)

I have no "Required Roles" set up on the individual roles or role group, yet I still get this message:
![image](https://user-images.githubusercontent.com/56011682/109376904-a2f56080-791b-11eb-92b1-c64c7cf2fdc0.png)

Any help would be appreciated. :)

**Comment by ShadowNight573** [comment]
Please join the support server on discord for help with these sorts of issues. Will have better luck getting an actual answer.
