### ISSUE TITLE
Trying to update preexisting menu, keeps giving me the error of "Invalid arguments provided: "-m XXX" is not a whole number"...

### ISSUE THREAD

**Issue by ddsh101** [jonas747/yagpdb#846]
I have the roles in the YAGPDB site, in my server. But it won't let me update the rolemenu for _any_ of the menus. I get the same error for _every_ menu.

![2037_spongelick - Copy](https://user-images.githubusercontent.com/80010978/110021278-26ce9480-7cf0-11eb-8fb8-d830653ae1cc.png)

**Comment by BlackWolfWoof** [comment]
Us rolemenu update without -m _also on the support server you will get help way faster :)_

**Comment by ddsh101** [comment]
> Us rolemenu update without -m _also on the support server you will get help way faster :)_

Ahhh thank you. I'm...not good with tech at all _and_ I have no idea what I'm doing. I appreciate the help!
