### ISSUE TITLE
Automod stopped working

### ISSUE THREAD

**Issue by foresta86** [jonas747/yagpdb#848]
Testing automod functions (don't mind the Regex).
Yesterday this rule was working fine for two members but not for one (NOT an Admin).
Today it stopped working completely.
Any ideas please?
![Screenshot 2021-03-08 223818](https://user-images.githubusercontent.com/25081296/110437302-81cc0700-80b5-11eb-9b0d-5237d2adcd80.png)
![Screenshot 2021-03-08 224731](https://user-images.githubusercontent.com/25081296/110437306-82fd3400-80b5-11eb-90e2-a42146c707de.png)

**Comment by BlackWolfWoof** [comment]
I am kinda busy right now bu if you send me your server id i can check your dashboard and maybe give you some advice. Lets switch to the discord chat for that one though
