### ISSUE TITLE
Remove Leave DM in Custom Commands

### ISSUE THREAD

**Issue by haydenwalker980** [jonas747/yagpdb#850]
Servers abuse this to kinda get more members and it just seems sucky

**Comment by haydenwalker980** [comment]
![image](https://user-images.githubusercontent.com/37120379/110905051-b7900c00-82be-11eb-965b-fcaec5f4bf58.png)  
Rather spammy and the first one falls under DM advertising (I believe)

**Comment by BlackWolfWoof** [comment]
Yep it does suck when people use that.
But it was possible for a long timr and wasn't a problem until now.
I have no idea why it recently got so popular but i even had to make a text snippet about this![Screenshot_20210312-080840.jpg](https://user-images.githubusercontent.com/29355595/110905073-32cadf80-830a-11eb-8b70-f47183bf0f28.jpg)

Also suggesting changes here won't get people to vote for it. If you want you can join the [support server](https://discord.gg/4udtcA5) and use -suggest (after you have waited 1h) to suggest changes for the bot.

**Comment by haydenwalker980** [comment]
Alright I've done that.

**Comment by haydenwalker980** [comment]
Closing because this has now been implemented.
