### ISSUE TITLE
Calc fails when subtracting negative numbers or adding positive numbers

### ISSUE THREAD

**Issue by icecream17** [jonas747/yagpdb#860]
```js
2--1 // error instead of <two minus negative one: 3>
2+-1 // works with <two plus negative one: 1>
2-+1 // works with <two minus positive one: 1>
2++1 // error instead of <two plus positive one: 3>

2*+1 // works with other operators
```

**Comment by jo3-l** [comment]
Technically speaking this is an issue with the package we use for `-calc`:
https://github.com/jonas747/yagpdb/blob/2e558b68509e0de9adf33635ae1ab08accfe4350/stdcommands/calc/calc.go#L8

<https://github.com/alfredxing/calc>
...however it looks like that repository has been deprecated by its owner. Forking it would likely be the best solution, but I'd imagine this is relatively low priority. In the meantime, adding spaces seems to make it parse correctly:

![image](https://user-images.githubusercontent.com/56809242/113632743-95b94900-9620-11eb-8e68-4b6e1120f759.png)

**Comment by jonas747** [comment]
sending "\u200b" is a bit too hacky IMO, we should instead error out with a more helpfull message
