### ISSUE TITLE
Failed executing template: [...] Too many calls to this function

### ISSUE THREAD

**Issue by Kunshuu** [jonas747/yagpdb#868]
Hi,

First sorry for my english, that's not my main language !
I got a problem and i don't find any solution on web, often in custom command, i got a message:

"Failed executing template: template: CC #16:11:6: executing "CC #16" at <execCC 3 nil 1 (sdic...>: error calling execCC: Too many calls to this function",

so i looked at restriction at https://docs.yagpdb.xyz/commands/custom-commands.
There is one of my custom command for example:

`{{ $key := "EnEssai" }} 

{{ range $keys, $value := dbBottomEntries "EnEssai" 8 0 }}
	{{ $user := toInt64 $value.User.ID }}
	{{ $UserID := .User.ID }}
	{{ $Username := .User.Username }}
	{{ $Userdiscri := .User.Discriminator }}
	{{ $UserURL := (.User.AvatarURL "512") }}
	{{ if (eq (toInt $value.Value) 1) }}
		{{ if (dbGet $user "cooldownEnEssai") }}
		{{ else }}
			{{ execCC 3 nil 0 (sdict "UserID" $UserID "Username" $Username "UserDiscri" $Userdiscri "UserURL" $UserURL) }}
		{{ end }}
	{{ end }}
{{ end }}`

Custom command 3 is a command who will send an embed in specific channel after that.

To solve this error, i have edited this line from:
{{ range $keys, $value := dbBottomEntries "EnEssai" 8 0 }}
To:
{{ range $keys, $value := dbBottomEntries "EnEssai" 1 0 }}

The point is: i have a lot of user i want to check in DB, and with this configuration i can check only one, i need to check at least 5 user at the same time 

(to make it simple, i use these custome command to recruit some player in a video game, player who want to join us trigger a custom command that begin there recruitement and send an embed where i can accept or refuse them, if i accept them, they become member "in try" and i put a dbSetExpire who will expire 7 days laters in DB for them, every hour i have the custom command i've showed you to check if the dbSetExpire is still up or not, if it's not, then it send me an other embed to tell me "do you want to validate them ?")

I don't get why i got this message so, help to understand this would be appreciate a lot !

even with:

{{ range $keys, $value := dbBottomEntries "EnEssai" 2 0 }}

i still get this error :/

Again sorry for my english level, i hope you understood me !

**Comment by Wolveric** [comment]
This is a question better suited for the [support server.](https://discord.gg/4udtcA5) You can repost your script and what you're trying to achieve in the Custom Command help channel there.

**Comment by Kunshuu** [comment]
Okay, then i'll post my message there ! Thanks you
