### ISSUE TITLE
How to use list of regex for filter

### ISSUE THREAD

**Issue by Magnum97** [jonas747/yagpdb#870]
Its a word blacklist not a partial word blacklist...
time to start matching every word that contains the letter 
i dont see why you dont use regex instead?

_Originally posted by @buthed010203 in https://github.com/jonas747/yagpdb/issues/544#issuecomment-547662279_

**Comment by Magnum97** [comment]
How would I implement this? I have created a list of blacklisted words but in filter it only has "Words from blacklist" or "Matching regex" when I select "Matching Regex" it has a single line for input. Is it possible to use a list as regex?

**Comment by l-zeuch** [comment]
Please read carefully through the linked issue, as there is a solution given already.
Moreover, regular expressions function in a way which allows for very high customization, which is however linked with some "having to learn it".
You can get a more definite answer on the [support server](https://discord.com/invite/4udtcA5), issues on this repository should be kept for real issues with the bot, not for general questions.

**Comment by buthed010203** [comment]
You can always just use a custom command with a regex of .* and process multiple regexes inside of the command. Alternatively you can just use pipes, `hi|hello` would match either `hi` or `hello`

**Comment by Magnum97** [comment]
Thank you for the responses. After chatting on the discord server it seems I will just use a word list. ironically used regex to reformat my regex file to plain text :laughing:
