### ISSUE TITLE
Clean command returns and extra number

### ISSUE THREAD

**Issue by objectopensource** [jonas747/yagpdb#877]
When I use the `-clean` command with the number 5 for example, the bot deletes 5 messages just like it's supposed to, but it says that it deleted 6 messages after deleting them. It's adding 1 to the actual number.
```
-clean 5

Deleted 6 messages! :')
```

**Comment by LemmeCry** [comment]
When you run `-clean n`, you delete the previously sent n messages along with the an extra message, the one with the command. So the command does in fact delete `n+1` messages.

**Comment by objectopensource** [comment]
Understood, but it can be confusing sometimes, and other bots like MEE6 say they only deleted `n` messages, and I would recommend doing that with YAGPDB too.
