### ISSUE TITLE
Youtube: Reduce the quota used for each channel check by 2/3

### ISSUE THREAD

**Issue by jonas747** [jonas747/yagpdb#94]
Instead of querying content details, query only id, then check all the id's against a set in redis if they've been posted already, if they haven't then request further details/pagination.

I estimate that this will save 2/rds of the api quota. Which will allow me to increase the number of channels polled to 1k per 100 seconds, as opposed to the current maximum of around 350 ish.

This is not much of a priority now since its still aound 5 minutes delay on average and max 10 mins i believe. But if the bot grows then i can inrease the polling rate using this method.

**Comment by buthed010203** [comment]
@jonas747 Is this still relavent?

**Comment by jonas747** [comment]
To some extent, i still run the normal poller alongside incase the webserver was down for a moment and videos were missed.

**Comment by buthed010203** [comment]
I guess so
