### ISSUE TITLE
Reset Roles from Role Menu

### ISSUE THREAD

**Issue by Dexter95** [jonas747/yagpdb#974]
When I run the command -rolemenu resetreactions (Message ID) , it resets the the emoji reactions as expected but it does not take away the respective roles from the users who have reacted with the emojis to get a role. -rr flag is also true which states that removing reaction will remove the role. I looked through the documentation and could not find a way to take away the respective roles from users once I reset the reaction from the role menu. Please help

**Comment by l-zeuch** [comment]
That is intended behavior, as the only thing being reset is the rolemenu. It'd be way too confusing for our userbase if we also removed the role from all members who have that role.
If you want to remove a role from everyone, either delete the role or use a bot which has a command to mass-remove roles.

**Comment by Dexter95** [comment]
Thank you so much for the help.
