### ISSUE TITLE
Make stop another option for end

### ISSUE THREAD

**Issue by grantemj** [jonas747/yagpdb#986]
Just add an alias for `>cah stop` so that peeps can use `>cah stop`

I (and others) keep accidentally trying to use it lmao

**Comment by grantemj** [comment]
Oh poopie, wrong repo -_-

**Comment by Wolveric** [comment]
If you'd like to make a suggestion, you should make it though the suggestion pattern on YAGPDB's [support server.](https://discord.gg/yagpdb)
