### ISSUE TITLE
Give Role Command Is Not Able To Find Roles No Matter What

### ISSUE THREAD

**Issue by shk8s** [jonas747/yagpdb#996]
I've tried to use a clone bot version running the file [docker-compose.dev.yml ](https://github.com/jonas747/yagpdb/blob/master/yagpdb_docker/docker-compose.dev.yml) after i run this file using the command `docker-compose -f docker-compose.dev.yml up` of course inside of directory containing the file;

Once bots up and running out of box on clone version the `-giverole @user @role` command does not work nor the `/`(slash) command version

**Comment by l-zeuch** [comment]
Use the role name and not the mention. Please use the support server next time.
