### ISSUE TITLE
The "{{.User.(ID/Username/Mention/Discriminator/Bot)}}" text on the website confuses people

### ISSUE THREAD

**Issue by BlackWolfWoof** [jonas747/yagpdb#997]
I wanted to do a pr for this but uhhh i have no idea about html and also don't know how it should end up looking. The file you'd have to edit for this is cp_main.html
One or 2 examples like `{{.User.Mention}}. {{.User.Username}} [for more info see the docs](https://docs.yagpdb.xyz/reference/templates#user)` or something like that would be really good. The same goes for `{{.Author.(Username/ID/Discriminator)}}`, `{{.Server.(ID/Name/Icon/Owner/Permissions)}}`. Just so people don't ask why `{{.Author.(Username/ID/Discriminator)}}` gives them an error if they exactly copy and paste that into the response box.

Also jonas, check your dm, i messaged you something that I wanted to say about this here but can't because everyone would be able to see it.

Ah and one more thing... what actually is `{{.Server.Permissions}}`? I don't remember us being able to use that.

**Comment by l-zeuch** [comment]
Re: The helper text
I'll open a pull request changing that.

Re: `.Server.Permissions`
Doesn't look like it is properly exposed? I'm getting errors that this field can't be evaluated, join feed just fails. I think it's this:
https://discord.com/developers/docs/resources/guild#guild-object-guild-structure
(see `permissions?` there)
